baseURL = 'http://example.com/'
languageCode = 'zh'
defaultContentLanguage= 'zh'
theme = 'terminal'

[params]
contentTypeName = "posts"
centerTheme = true


[languages]
  [languages.zh]
    languageName = "Chinese"
    title = "ie12sBlog"

[languages.zh.params]
      subtitle = "A simple, retro theme for Hugo"
      owner = ""
      keywords = ""
      copyright = ""
      menuMore = "显示更多"
      readMore = "阅读更多"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "找不到页面……"
      missingBackButtonLabel = "返回主页"
      minuteReadingTime = "min read"
      words = "words"



      [languages.zh.params.logo]
        logoText = "ie12sBlog"
        logoHomeLink = "/"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
